/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JMenuItem;

/**
 *
 * @author User
 */
public class MenuLayanan extends javax.swing.JFrame {

    /**
     * Creates new form UserMenu
     */
    public MenuLayanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSurat = new javax.swing.JButton();
        btnBarang = new javax.swing.JButton();
        btnUang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDokumen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu = new javax.swing.JMenu();
        menuAwal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(202, 194, 166));

        btnSurat.setBackground(new java.awt.Color(202, 194, 166));
        btnSurat.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnSurat.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\TUBES PBO\\surat_icon.png")); // NOI18N
        btnSurat.setText(" Pengiriman Surat");
        btnSurat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSurat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnBarang.setBackground(new java.awt.Color(202, 194, 166));
        btnBarang.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnBarang.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\TUBES PBO\\barang_icon.png")); // NOI18N
        btnBarang.setText(" Pengiriman Barang");
        btnBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnUang.setBackground(new java.awt.Color(202, 194, 166));
        btnUang.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnUang.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Pictures\\TUBES PBO\\uang_icon.png")); // NOI18N
        btnUang.setText(" Pengiriman Uang");
        btnUang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUangActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setText("Bojongsoang Post Office Services");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logo.png"))); // NOI18N

        btnDokumen.setBackground(new java.awt.Color(202, 194, 166));
        btnDokumen.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnDokumen.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\document_icon-icons.com_66534.png")); // NOI18N
        btnDokumen.setText(" Pengiriman Dokumen");
        btnDokumen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDokumen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDokumen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSurat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btnDokumen)
                        .addGap(18, 18, 18)
                        .addComponent(btnBarang)
                        .addGap(18, 18, 18)
                        .addComponent(btnUang)
                        .addGap(18, 18, 18)
                        .addComponent(btnSurat)))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        JMenu.setText("File");
        JMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuAwal.setText("Menu Awal");
        menuAwal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JMenu.add(menuAwal);

        jMenuBar1.add(JMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUangActionPerformed

    /**
     * @param args the command line arguments
     */

    public void addActionListener(ActionListener e){
        btnBarang.addActionListener(e);
        btnDokumen.addActionListener(e);
        btnUang.addActionListener(e);
        btnSurat.addActionListener(e);
        menuAwal.addActionListener(e);
    }
    
    public void setBarang(String s) {
        this.btnBarang.setText(s);
    }

    public void setDokumen(String s) {
        this.btnDokumen.setText(s);
    }

    public void setSurat(String s) {
        this.btnSurat.setText(s);
    }

    /**
     * @param args the command line arguments
     */
    public void setUang(String s) {
        this.btnUang.setText(s);
    }
    
    public JButton getDokumen(){
        return this.btnDokumen;
    }
    
    public JButton getBarang(){
        return this.btnBarang;
    }
    
    public JButton getSurat(){
        return this.btnSurat;
    }
    
    public JButton getUang(){
        return this.btnUang;
    }
    
    public JMenuItem getMenuAwal(){
        return this.menuAwal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu;
    private javax.swing.JButton btnBarang;
    private javax.swing.JButton btnDokumen;
    private javax.swing.JButton btnSurat;
    private javax.swing.JButton btnUang;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuAwal;
    // End of variables declaration//GEN-END:variables
}
